// This file was auto-generated by prisma-generator-typescript-interfaces

export type Role = "ADMIN" | "USER";

export type ShipmentStatus = "PENDING" | "COMPLETED" | "CANCELLED";

export type ProjectStatus = "ACTIVE" | "COMPLETED" | "ARCHIVED";

export type DocumentType = "SPECIFICATION" | "DRAWING" | "CONTRACT" | "OTHER";

export type CostType = "MATERIAL" | "LABOR";

export interface User {
  id: string;
  username: string;
  password: string;
  firstName: string;
  lastName: string;
  role: Role[];
  email: string;
  phone: string;
  age: number;
  address: string;
  avatar: string;
  createdAt: Date;
  updatedAt: Date;
  tokens?: Token[];
}

export interface Token {
  token: string;
  expires: Date;
  userId: string;
  user?: User;
}

export interface Product {
  id: string;
  title: string;
  description: string;
  category: string;
  manufacturer: string;
  imageUrl: string;
  unit: string;
  images?: ProductImage[];
  shipmentItems?: ShipmentItem[];
  stockItems?: StockItem[];
}

export interface ProductImage {
  id: string;
  productId: string;
  url: string;
  product?: Product;
}

export interface Message {
  id: number;
  userId: string;
  userName: string;
  text: string;
  createdAt: Date;
  attachments?: Attachment[];
}

export interface Attachment {
  id: string;
  messageId: number;
  message?: Message;
  fileName: string;
  fileSize: number;
  fileType: string;
  filePath: string;
  uploadedAt: Date;
}

export interface Warehouse {
  id: string;
  name: string;
  address: string | null;
  createdAt: Date;
  updatedAt: Date;
  stockItems?: StockItem[];
  shipments?: Shipment[];
}

export interface StockItem {
  id: string;
  productId: string;
  warehouseId: string;
  quantity: number;
  purchasePrice: number | null;
  estimatePrice: number | null;
  salePrice: number | null;
  discount: number | null;
  createdAt: Date;
  updatedAt: Date;
  product?: Product;
  warehouse?: Warehouse;
}

export interface Object {
  id: string;
  name: string;
  address: string | null;
  description: string | null;
  createdAt: Date;
  updatedAt: Date;
  shipments?: Shipment[];
}

export interface Shipment {
  id: string;
  warehouseId: string;
  objectId: string;
  status: ShipmentStatus;
  createdAt: Date;
  updatedAt: Date;
  warehouse?: Warehouse;
  object?: Object;
  items?: ShipmentItem[];
}

export interface ShipmentItem {
  id: string;
  shipmentId: string;
  productId: string;
  quantity: number;
  createdAt: Date;
  shipment?: Shipment;
  product?: Product;
}

export interface Project {
  id: string;
  name: string;
  description: string | null;
  createdAt: Date;
  updatedAt: Date;
  images?: ProjectImage[];
  documents?: ProjectDocument[];
  estimate?: Estimate | null;
  status: ProjectStatus;
}

export interface ProjectImage {
  id: string;
  projectId: string;
  project?: Project;
  data: Uint8Array;
  filename: string;
  mimeType: string;
  size: number;
  createdAt: Date;
  sortOrder: number;
}

export interface ProjectDocument {
  id: string;
  projectId: string;
  project?: Project;
  data: Uint8Array;
  filename: string;
  mimeType: string;
  size: number;
  createdAt: Date;
  docType: DocumentType;
}

export interface Estimate {
  id: string;
  projectId: string;
  project?: Project;
  items?: EstimateItem[];
  totalCost: number;
  laborCost: number | null;
  materialsCost: number | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface EstimateItem {
  id: string;
  estimateId: string;
  estimate?: Estimate;
  productId: string | null;
  name: string;
  description: string | null;
  quantity: number;
  unit: string;
  price: number;
  total: number;
  costType: CostType;
}
